batched up writing to file per shellcheck's suggestion

diff --git a/mksh b/mksh
--- a/mksh
+++ b/mksh
@@ -11,11 +11,13 @@ elif [ -e "$1" ]; then
 	exit 1
 fi
 
-echo '#!/usr/bin/env bash' >"$1"
-echo 'set -e              # Exit immediately if a pipeline returns a non-zero status.' >>"$1"
-echo 'set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.' >>"$1"
-echo 'set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. ' >>"$1"
-echo >>"$1"
+{
+	echo '#!/usr/bin/env bash'
+	echo 'set -e              # Exit immediately if a pipeline returns a non-zero status.'
+	echo 'set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.'
+	echo 'set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. '
+	echo
+} >>"$1"
 
 chmod u+x "$1"
 
