formatted all files with shfmt --indent 2 --case-indent --write --simplify [^R]*

diff --git a/mksh b/mksh
--- a/mksh
+++ b/mksh
@@ -4,19 +4,19 @@ set -u          # Treat unset variables and parameters other than the special pa
 set -o pipefail # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully.
 
 if [ ! $# -eq 1 ]; then
-	echo 'makesh takes one argument' 1>&2
-	exit 1
+  echo 'makesh takes one argument' 1>&2
+  exit 1
 elif [ -e "$1" ]; then
-	echo "$1 already exists" 1>&2
-	exit 1
+  echo "$1 already exists" 1>&2
+  exit 1
 fi
 
 {
-	echo '#!/usr/bin/env bash'
-	echo 'set -e              # Exit immediately if a pipeline returns a non-zero status.'
-	echo 'set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.'
-	echo 'set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. '
-	echo
+  echo '#!/usr/bin/env bash'
+  echo 'set -e              # Exit immediately if a pipeline returns a non-zero status.'
+  echo 'set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.'
+  echo 'set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. '
+  echo
 } >>"$1"
 
 chmod u+x "$1"
diff --git a/screenshotcompress b/screenshotcompress
--- a/screenshotcompress
+++ b/screenshotcompress
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
-set -e              # Exit immediately if a pipeline returns a non-zero status.
-set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
-set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. 
+set -e          # Exit immediately if a pipeline returns a non-zero status.
+set -u          # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
+set -o pipefail # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully.
 
 # This script makes it really easy to compress screen shots before pasting them into emails or Jira cases.
 #
@@ -17,19 +17,18 @@ set -o pipefail     # Return value of a pipeline is the value of the last (right
 # https://medium.com/macoclock/how-to-make-a-workflow-to-auto-compress-the-screenshot-from-mac-and-copy-it-to-clipboard-79c1c28598db
 # https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html#//apple_ref/doc/uid/10000172i-SW7-SW8
 
-for FILE in "$@"
-do
-    FILE_LOWER=$(echo "$FILE" | tr '[:upper:]' '[:lower:]')
+for FILE in "$@"; do
+  FILE_LOWER=$(echo "$FILE" | tr '[:upper:]' '[:lower:]')
 
-    # don't recompress the new file
-	if [[ "$FILE_LOWER" =~ (-min\.png$) ]]; then exit; fi
+  # don't recompress the new file
+  if [[ "$FILE_LOWER" =~ (-min\.png$) ]]; then exit; fi
 
-    # only compress PNG files
-	if [[ ! "$FILE_LOWER" =~ (\.png$) ]]; then exit; fi
+  # only compress PNG files
+  if [[ ! "$FILE_LOWER" =~ (\.png$) ]]; then exit; fi
 
-	/usr/local/bin/pngquant 128 --skip-if-larger --strip --ext=-min.png -- "$FILE"
+  /usr/local/bin/pngquant 128 --skip-if-larger --strip --ext=-min.png -- "$FILE"
 
-    # open the newly compressed file
-    NEW_FILE=$(echo "$FILE" | sed -E 's/\.png$/-min.png/i')
-    open "$NEW_FILE"
+  # open the newly compressed file
+  NEW_FILE=$(echo "$FILE" | sed -E 's/\.png$/-min.png/i')
+  open "$NEW_FILE"
 done
