used shfmt to reformat all files

diff --git a/rmasync b/rmasync
--- a/rmasync
+++ b/rmasync
@@ -1,20 +1,20 @@
 #!/usr/bin/env bash
-set -e              # Exit immediately if a pipeline returns a non-zero status.
-set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
-set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. 
+set -e          # Exit immediately if a pipeline returns a non-zero status.
+set -u          # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
+set -o pipefail # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully.
 
 # Deleting ginormous folders, like log folders, .m2, or node folders can take awhile.
 # This script will move the folder to a temp directory, which is fast, and then recursively delete the folder asynchronously
 
 if [[ ! $# -eq 1 ]]; then
-    echo "blah blah 1"
-    exit 1;
+	echo "blah blah 1"
+	exit 1
 fi
 
 # make sure it's a folder
 if [[ ! -d "$1" ]]; then
-    echo "blah blah 2"
-    exit 1;
+	echo "blah blah 2"
+	exit 1
 fi
 
 destfolder=$(mktemp -d /tmp/deleteme-rmasync-XXXXX)
