.

diff --git a/timer b/timer
--- a/timer
+++ b/timer
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
-set -e              # Exit immediately if a pipeline returns a non-zero status.
-set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
-set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. 
+set -e          # Exit immediately if a pipeline returns a non-zero status.
+set -u          # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
+set -o pipefail # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully.
 
 MINS=$1
 SECONDS=$((MINS * 60))
@@ -10,14 +10,14 @@ MESSAGE="Time's Up: $MINS minute(s)"
 # If there's a second parameter, use it for the title
 TITLE="Timer"
 if [ "$#" -eq 2 ]; then
-    TITLE="$2"
+  TITLE="$2"
 fi
 
 notify() {
   local message="$1"
   local title="$2"
   say 'beep, beep, beep' &
-  osascript -e "tell application \"System Events\" to display dialog \"${message}\" with title \"${title}\"" > /dev/null &
+  osascript -e "tell application \"System Events\" to display dialog \"${message}\" with title \"${title}\"" >/dev/null &
 }
 
 Sleep "$SECONDS" && notify "$MESSAGE" "$TITLE" &
