making urlexists more consistent with other scripts

diff --git a/urlexists b/urlexists
--- a/urlexists
+++ b/urlexists
@@ -1,13 +1,6 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -e              # Exit immediately if a pipeline returns a non-zero status.
+set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
+set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. 
 
-# -L - follow redirects
-# -I - headers only
-# -s - silent - don't show progress meter
-# -w - write-out - write to stdout
-val=$(curl -LI "$1" -o /dev/null -w '%{http_code}\n' -s)
-if [[ "$val" = 200 ]]; then
-    exit 0
-else
-    # return the http status code
-    exit $?
-fi
+curl -LI "$1" -o /dev/null -w '%{http_code}\n' -s
