made the versionmanager script more consistent with the other scripts

diff --git a/versionmanager b/versionmanager
--- a/versionmanager
+++ b/versionmanager
@@ -1,18 +1,19 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -e              # Exit immediately if a pipeline returns a non-zero status.
+set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
+set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. 
 
-# if no parameter, then just go to stash
 if [[ $# -eq 0 ]]; then
-    open https://versionmanager.arbfund.com
-    exit 0
-fi
-
-# if parameter is "." then use the current path
-if [[ "$1" = "." ]]; then
+    "$BROWSER" https://versionmanager.arbfund.com
+elif [[ "$1" = "--help" ]]; then
+    echo "NAME"
+    echo "  versionmanager --help"
+    echo "  versionmanager"
+    echo "  versionmanager [project name]"
+    echo "  versionmanager ."
+elif [[ "$1" = "." ]]; then
     val=${PWD##*/}
-    open https://versionmanager.arbfund.com/#/projects/"$val"\?ac=settings
-    exit 0
+    "$BROWSER" https://versionmanager.arbfund.com/#/projects/"$val"\?ac=settings
+else
+    "$BROWSER" https://versionmanager.arbfund.com/#/projects/"$1"\?ac=settings
 fi
-
-# else go to the path passed in
-open https://versionmanager.arbfund.com/#/projects/"$1"\?ac=settings
-exit 0
